version: "3.9"

services:
  fhir:
    image: docker.io/hapiproject/hapi:v6.6.0@sha256:c00367865ae5dad4e171cbb68bfc1c39818854079d1565bee4c86a45e78335d0
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "false"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
    ports:
      - 8082:8080

  zoo1:
    image: docker.io/library/zookeeper:3.8.1@sha256:c57913ca16e9753417401eea0ffeb4f2914b17b595fcac53b98ad620ab5665d4
    restart: unless-stopped
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: docker.io/confluentinc/cp-kafka:7.4.0@sha256:187dac6627e7906c350f5f8c982f80ce735ff1a0e571a20de6000a309a12ce63
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zoo1

  akhq:
    image: docker.io/tchiotludo/akhq:0.24.0@sha256:6ccf8323ae6e93a893107f857cd9f7210add3569743b2c8528c6567967cc636f
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka1:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 9000:8080
    depends_on:
      - kafka1

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.45@sha256:5d5c9d2d8c8cbb42f1db4aac1f1f8487bac63da6802004d0da8580fc0c7311a1
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp

  mock-data-loader:
    image: docker.io/confluentinc/cp-kafkacat:7.1.7@sha256:78b5a1a1702244e12ba17d205e908c722b9fc66596af737a2263d7d88cad0867
    entrypoint: ["/bin/bash", "-c"]
    restart: on-failure
    command:
      [
        "while true; do kafkacat -b kafka1:19092 -t fhir-msg -P -l /data/mock-data.ndjson; sleep 10; done",
      ]
    volumes:
      - ${PWD}/hack/mock-data.ndjson:/data/mock-data.ndjson:ro
    depends_on:
      - kafka1
