version: "3.9"

services:
  fhir:
    image: docker.io/hapiproject/hapi:v6.2.2@sha256:9c4e8af94d81ac0049dbb589e4cd855bf78c9c13be6f6844e814c63d63545b44
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "false"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
    ports:
      - 8082:8080

  zoo1:
    image: docker.io/library/zookeeper:3.8.0@sha256:907227c11e8ad438abc3d8d8c545d006862274a2014756f3eb61c20eb80a33b0
    restart: unless-stopped
    hostname: zoo1
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181

  kafka1:
    image: docker.io/confluentinc/cp-kafka:7.3.1@sha256:92f3fbd7693fd50858b798114b4886cd36bf51793f54059620c68ba4d97f8f8e
    hostname: kafka1
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
    depends_on:
      - zoo1

  akhq:
    image: docker.io/tchiotludo/akhq:0.23.0@sha256:6beade9f8c3fe19d76bebeb525a20d005cfe75fdc2e7b4df7847a1a8085e2d2d
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            kafka1:
              properties:
                bootstrap.servers: "kafka1:19092"
    ports:
      - 9000:8080
    depends_on:
      - kafka1

  jaeger:
    image: docker.io/jaegertracing/all-in-one:1.40@sha256:fa8c1fc551ac31e161a7f729dbaf17e46aaccb0dbd5fbd772aeeb209802cb2a0
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp

  mock-data-loader:
    image: docker.io/confluentinc/cp-kafkacat:7.1.5@sha256:bd7efa265abe3f8fc31d2e812b9237cc08b1839bfd14b2a818de5b2ce869d9be
    entrypoint: ["/bin/bash", "-c"]
    restart: on-failure
    command:
      [
        "while true; do kafkacat -b kafka1:19092 -t fhir-msg -P -l /data/mock-data.ndjson; sleep 10; done",
      ]
    volumes:
      - ${PWD}/hack/mock-data.ndjson:/data/mock-data.ndjson:ro
    depends_on:
      - kafka1
