apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: fhir-to-server
build:
  artifacts:
    - image: ghcr.io/miracum/fhir-to-server
      context: .
manifests:
  rawYaml:
    - k8s/*.yaml
deploy:
  kubectl: {}
