apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: fhir-to-server
build:
  local:
    concurrency: 1
    tryImportMissing: false
    useDockerCLI: true
    push: false
    useBuildkit: true
  artifacts:
    - image: ghcr.io/miracum/kafka-fhir-to-server
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      context: .
manifests:
  helm:
    releases:
      - name: akhq
        remoteChart: akhq
        repo: https://akhq.io/
        version: 0.24.0
        skipBuildDependencies: true
        wait: true
        valuesFiles:
          - "k8s/akhq-values.yaml"
      - name: hapi-fhir-jpaserver
        remoteChart: hapi-fhir-jpaserver
        repo: https://hapifhir.github.io/hapi-fhir-jpaserver-starter
        version: 0.11.0
        skipBuildDependencies: true
        wait: true
        setValues:
          # kics-scan ignore-line
          postgresql.auth.postgresPassword: fhir
      - name: stream-processors
        remoteChart: stream-processors
        repo: https://miracum.github.io/charts
        version: 1.1.8
        skipBuildDependencies: true
        wait: true
        valuesFiles:
          - "k8s/stream-processors-values.yaml"
deploy:
  helm: {}
