configuration:
  akhq:
    server:
    connections:
      my-cluster: # url friendly name for the cluster (letter, number, _, -, ... dot are not allowed here)
        properties: # standard kafka properties (optional)
          bootstrap.servers: "my-cluster-kafka-bootstrap:9092"
