apiVersion: v1
kind: Pod
metadata:
  name: fhir-to-server
spec:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: fhir-to-server
      image: ghcr.io/miracum/fhir-to-server:v1.1.3
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        privileged: false
        runAsGroup: 65532
        runAsUser: 65532
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      resources:
        limits:
          memory: 1Gi
          cpu: 1000m
        requests:
          memory: 1Gi
          cpu: 1000m
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /actuator/health/liveness
          port: http
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: http
      env:
        - name: BOOTSTRAP_SERVERS
          value: my-cluster-kafka-bootstrap:9093
        - name: TOPIC
          value: fhir-msg
        - name: GROUP_ID
          value: fhir-to-server
        - name: DISABLE_AUTO_COMMIT
          value: "false"
        - name: FHIR_URL
          value: http://fhir-server:8080/fhir
        - name: SECURITY_PROTOCOL
          value: SSL
        - name: SSL_KEY_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: fhir-to-server-user
              key: user.password
        - name: SSL_TRUST_STORE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-cluster-cluster-ca-cert
              key: ca.password
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:MaxRAMPercentage=50 -XX:G1PeriodicGCInterval=1000 -XX:G1PeriodicGCSystemLoadThreshold=1000"
      volumeMounts:
        - name: cluster-certs
          mountPath: /opt/kafka-certs/ca.p12
          subPath: ca.p12
          readOnly: true
        - name: user-certs
          mountPath: /opt/kafka-certs/user.p12
          subPath: user.p12
          readOnly: true
  volumes:
    - name: cluster-certs
      secret:
        secretName: my-cluster-cluster-ca-cert
    - name: user-certs
      secret:
        secretName: fhir-to-server-user
