name: "Validate Gradle Wrapper"
on: [push, pull_request]

permissions: read-all

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.6
