name: "Validate Gradle Wrapper"
on: [pull_request]

permissions: read-all

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4 # v1.1.0
