name: "Validate Gradle Wrapper"
on: [pull_request]

permissions: read-all

jobs:
  validate:
    name: "validate"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.6
