name: "Verify base image signature"
on: [pull_request]

permissions: read-all

jobs:
  validate:
    name: "verify dockerfile"
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
      - name: Install Cosign
        uses: sigstore/cosign-installer@dd6b2e2b610a11fd73dd187a43d57cc1394e35f9 # v3.0.5
      - run: |
          cosign dockerfile verify \
                --output text \
                --base-image-only \
                --certificate-oidc-issuer https://accounts.google.com \
                --certificate-identity keyless@distroless.iam.gserviceaccount.com \
                Dockerfile
