name: "Verify base image signature"
on: [pull_request]

permissions: read-all

jobs:
  validate:
    name: verify
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
      - name: Install Cosign
        uses: sigstore/cosign-installer@6e04d228eb30da1757ee4e1dd75a0ec73a653e06 # v3.1.1
      - run: |
          cosign dockerfile verify \
                --output text \
                --base-image-only \
                --certificate-oidc-issuer https://accounts.google.com \
                --certificate-identity keyless@distroless.iam.gserviceaccount.com \
                Dockerfile
